CREATE FUNCTION [secured].[INBASKET_TASK](
    @type VARCHAR(32),
    @identity_list VARCHAR(MAX),
    @ip_address VARCHAR(32),
    @cur_user_id CHAR(32),
    @perms_having_can_get NVARCHAR(MAX),
    @env_attrs XML
)
    RETURNS TABLE
        AS
        RETURN
            (
                SELECT [secured].[PROJECT_TASK].assigned_to               AS assigned_to,
                       [secured].[PROJECT_TASK].classification            AS classification,
                       [secured].[PROJECT_TASK].closed_date               AS closed_date,
                       [secured].[PROJECT_TASK].config_id                 AS config_id,
                       [secured].[PROJECT_TASK].container                 AS container,
                       [secured].[PROJECT_TASK].container_type_id         AS container_type_id,
                       [secured].[PROJECT_TASK].created_by_id             AS created_by_id,
                       [secured].[PROJECT_TASK].created_on                AS created_on,
                       [secured].[PROJECT_TASK].css                       AS css,
                       [secured].[PROJECT_TASK].current_state             AS current_state,
                       [secured].[PROJECT_TASK].due_date                  AS due_date,
                       [secured].[PROJECT_TASK].generation                AS generation,
                       [secured].[PROJECT_TASK].icon                      AS icon,
                       [secured].[PROJECT_TASK].id                        AS id,
                       [secured].[PROJECT_TASK].instructions              AS instructions,
                       [secured].[PROJECT_TASK].is_current                AS is_current,
                       [secured].[PROJECT_TASK].is_done                   AS is_done,
                       [secured].[PROJECT_TASK].is_mine                   AS is_mine,
                       [secured].[PROJECT_TASK].is_released               AS is_released,
                       [secured].[PROJECT_TASK].is_waiting                AS is_waiting,
                       [secured].[PROJECT_TASK].item                      AS item,
                       [secured].[PROJECT_TASK].item_type_id              AS item_type_id,
                       [secured].[PROJECT_TASK].keyed_name                AS keyed_name,
                       [secured].[PROJECT_TASK].language_code_filter      AS language_code_filter,
                       [secured].[PROJECT_TASK].locked_by_id              AS locked_by_id,
                       [secured].[PROJECT_TASK].major_rev                 AS major_rev,
                       [secured].[PROJECT_TASK].managed_by_id             AS managed_by_id,
                       [secured].[PROJECT_TASK].minor_rev                 AS minor_rev,
                       [secured].[PROJECT_TASK].modified_by_id            AS modified_by_id,
                       [secured].[PROJECT_TASK].modified_on               AS modified_on,
                       [secured].[PROJECT_TASK].my_assignment             AS my_assignment,
                       [secured].[PROJECT_TASK].name                      AS name,
                       [secured].[PROJECT_TASK].new_version               AS new_version,
                       [secured].[PROJECT_TASK].not_lockable              AS not_lockable,
                       [secured].[PROJECT_TASK].owned_by_id               AS owned_by_id,
                       [secured].[PROJECT_TASK].permission_id             AS permission_id,
                       [secured].[PROJECT_TASK].start_date                AS start_date,
                       [secured].[PROJECT_TASK].state                     AS state,
                       [secured].[PROJECT_TASK].status                    AS status,
                       [secured].[PROJECT_TASK].team_id                   AS team_id,
                       COALESCE('9DC36DF7F0234A3E8CFFE2A20AB78CCE', NULL) AS ITEMTYPE,
                       [secured].[PROJECT_TASK].id_$_permission           AS id_$_permission
                FROM [secured].[PROJECT_TASK](@type, @identity_list, @ip_address, @cur_user_id, @perms_having_can_get,
                                              @env_attrs)
                UNION ALL
                SELECT [secured].[WORKFLOW_TASK].assigned_to              AS assigned_to,
                       [secured].[WORKFLOW_TASK].classification           AS classification,
                       [secured].[WORKFLOW_TASK].closed_date              AS closed_date,
                       [secured].[WORKFLOW_TASK].config_id                AS config_id,
                       [secured].[WORKFLOW_TASK].container                AS container,
                       [secured].[WORKFLOW_TASK].container_type_id        AS container_type_id,
                       [secured].[WORKFLOW_TASK].created_by_id            AS created_by_id,
                       [secured].[WORKFLOW_TASK].created_on               AS created_on,
                       [secured].[WORKFLOW_TASK].css                      AS css,
                       [secured].[WORKFLOW_TASK].current_state            AS current_state,
                       [secured].[WORKFLOW_TASK].due_date                 AS due_date,
                       [secured].[WORKFLOW_TASK].generation               AS generation,
                       [secured].[WORKFLOW_TASK].icon                     AS icon,
                       [secured].[WORKFLOW_TASK].id                       AS id,
                       [secured].[WORKFLOW_TASK].instructions             AS instructions,
                       [secured].[WORKFLOW_TASK].is_current               AS is_current,
                       [secured].[WORKFLOW_TASK].is_done                  AS is_done,
                       [secured].[WORKFLOW_TASK].is_mine                  AS is_mine,
                       [secured].[WORKFLOW_TASK].is_released              AS is_released,
                       [secured].[WORKFLOW_TASK].is_waiting               AS is_waiting,
                       [secured].[WORKFLOW_TASK].item                     AS item,
                       [secured].[WORKFLOW_TASK].item_type_id             AS item_type_id,
                       [secured].[WORKFLOW_TASK].keyed_name               AS keyed_name,
                       [secured].[WORKFLOW_TASK].language_code_filter     AS language_code_filter,
                       [secured].[WORKFLOW_TASK].locked_by_id             AS locked_by_id,
                       [secured].[WORKFLOW_TASK].major_rev                AS major_rev,
                       [secured].[WORKFLOW_TASK].managed_by_id            AS managed_by_id,
                       [secured].[WORKFLOW_TASK].minor_rev                AS minor_rev,
                       [secured].[WORKFLOW_TASK].modified_by_id           AS modified_by_id,
                       [secured].[WORKFLOW_TASK].modified_on              AS modified_on,
                       [secured].[WORKFLOW_TASK].my_assignment            AS my_assignment,
                       [secured].[WORKFLOW_TASK].name                     AS name,
                       [secured].[WORKFLOW_TASK].new_version              AS new_version,
                       [secured].[WORKFLOW_TASK].not_lockable             AS not_lockable,
                       [secured].[WORKFLOW_TASK].owned_by_id              AS owned_by_id,
                       [secured].[WORKFLOW_TASK].permission_id            AS permission_id,
                       [secured].[WORKFLOW_TASK].start_date               AS start_date,
                       [secured].[WORKFLOW_TASK].state                    AS state,
                       [secured].[WORKFLOW_TASK].status                   AS status,
                       [secured].[WORKFLOW_TASK].team_id                  AS team_id,
                       COALESCE('321BD822949149C597FD596B1212B85C', NULL) AS ITEMTYPE,
                       [secured].[WORKFLOW_TASK].id_$_permission          AS id_$_permission
                FROM [secured].[WORKFLOW_TASK](@type, @identity_list, @ip_address, @cur_user_id, @perms_having_can_get,
                                               @env_attrs)
            )