select RELATED_ID
from innovator.HS_PART_EXPRESS_REL_DETAIL;

select HS_PART from innovator.HS_PART_EXPRESS_REL_DETAIL;

--update innovator.HS_PART_EXPRESS_REL_DETAIL set RELATED_ID = null;

select PART.id,PART.KEYED_NAME,PART.NAME,LIFE_CYCLE_STATE.LABEL_ZC as State,PART.MAJOR_REV,PART.GENERATION from innovator.PART
join innovator.LIFE_CYCLE_STATE on innovator.PART.CURRENT_STATE = innovator.LIFE_CYCLE_STATE.ID
where PART.id in('5CC84159332642568CF40AD9E17822EE')
